### ISSUE TITLE
AttributeError: 'ExprConcat' object has no attribute 'urem'

### ISSUE THREAD

**Issue by windy1946** [quarkslab/arybo#11]
> Should be fixed with [38dd93c](https://github.com/quarkslab/arybo/commit/38dd93c920d0c0f16090346dd839979d750f7259)

I have tried the `getType()`, but it still have another error.
the log said that `AttributeError: 'ExprConcat' object has no attribute 'urem'`
here is the complete log.
```
[+] Generating symbolic_expressions/sample4-unprotected.bin.py
[+] Converting symbolic expressions to an LLVM module...
Traceback (most recent call last):
  File "./solve-vm.py", line 761, in <module>
    retValue  = main()
  File "./solve-vm.py", line 671, in main
    M = generateLLVMExpressions(ctx, 0)
  File "./solve-vm.py", line 623, in generateLLVMExpressions
    e = tritonexprs2arybo(exprs)
  File "~/.local/lib/python2.7/site-packages/arybo/tools/triton_.py", line 169, in tritonexprs2arybo
    e = tritonast2arybo(e.getAst(), True, False, context)
  File "~/.local/lib/python2.7/site-packages/arybo/tools/triton_.py", line 36, in tritonast2arybo
    v = next(children)
  File "~/.local/lib/python2.7/site-packages/arybo/tools/triton_.py", line 30, in <genexpr>
    children = (tritonast2arybo(c,use_exprs,use_esf,context) for c in children_)
  File "~/.local/lib/python2.7/site-packages/arybo/tools/triton_.py", line 60, in tritonast2arybo
    v = next(children)
  File "~/.local/lib/python2.7/site-packages/arybo/tools/triton_.py", line 30, in <genexpr>
    children = (tritonast2arybo(c,use_exprs,use_esf,context) for c in children_)
  File "~/.local/lib/python2.7/site-packages/arybo/tools/triton_.py", line 139, in tritonast2arybo
    return reduce(binop, children)
  File "~/.local/lib/python2.7/site-packages/arybo/tools/triton_.py", line 132, in <lambda>
    TAstN.BVUREM: lambda x,y: x.urem(y),
AttributeError: 'ExprConcat' object has no attribute 'urem'
Command exited with non-zero status 1
```

_Originally posted by @windy1946 in https://github.com/quarkslab/arybo/issue_comments#issuecomment-456111753_

**Comment by windy1946** [comment]
> > Should be fixed with [38dd93c](https://github.com/quarkslab/arybo/commit/38dd93c920d0c0f16090346dd839979d750f7259)
> 
> I have tried the `getType()`, but it still have another error.
> the log said that `AttributeError: 'ExprConcat' object has no attribute 'urem'`
> here is the complete log.
> 
> ```
> [+] Generating symbolic_expressions/sample4-unprotected.bin.py
> [+] Converting symbolic expressions to an LLVM module...
> Traceback (most recent call last):
>   File "./solve-vm.py", line 761, in <module>
>     retValue  = main()
>   File "./solve-vm.py", line 671, in main
>     M = generateLLVMExpressions(ctx, 0)
>   File "./solve-vm.py", line 623, in generateLLVMExpressions
>     e = tritonexprs2arybo(exprs)
>   File "~/.local/lib/python2.7/site-packages/arybo/tools/triton_.py", line 169, in tritonexprs2arybo
>     e = tritonast2arybo(e.getAst(), True, False, context)
>   File "~/.local/lib/python2.7/site-packages/arybo/tools/triton_.py", line 36, in tritonast2arybo
>     v = next(children)
>   File "~/.local/lib/python2.7/site-packages/arybo/tools/triton_.py", line 30, in <genexpr>
>     children = (tritonast2arybo(c,use_exprs,use_esf,context) for c in children_)
>   File "~/.local/lib/python2.7/site-packages/arybo/tools/triton_.py", line 60, in tritonast2arybo
>     v = next(children)
>   File "~/.local/lib/python2.7/site-packages/arybo/tools/triton_.py", line 30, in <genexpr>
>     children = (tritonast2arybo(c,use_exprs,use_esf,context) for c in children_)
>   File "~/.local/lib/python2.7/site-packages/arybo/tools/triton_.py", line 139, in tritonast2arybo
>     return reduce(binop, children)
>   File "~/.local/lib/python2.7/site-packages/arybo/tools/triton_.py", line 132, in <lambda>
>     TAstN.BVUREM: lambda x,y: x.urem(y),
> AttributeError: 'ExprConcat' object has no attribute 'urem'
> Command exited with non-zero status 1
> ```
> 
> _Originally posted by @windy1946 in https://github.com/quarkslab/arybo/issue_comments#issuecomment-456111753_

this problem is fixed after i use the latest release.
it is 1.0 version when i use `pip` to install the arbo.
