### ISSUE TITLE
llvmlite should be added as a dependency

### ISSUE THREAD

**Issue by JJK96** [quarkslab/arybo#16]
```
Traceback (most recent call last):
  File "./solve-vm.py", line 760, in <module>
    retValue  = main()
  File "./solve-vm.py", line 670, in main
    M = generateLLVMExpressions(ctx, 0)
  File "./solve-vm.py", line 625, in generateLLVMExpressions
    M = to_llvm_function(e,[var.v])
  File "build/bdist.linux-x86_64/egg/arybo/lib/exprs_asm.py", line 201, in to_llvm_function
RuntimeError: llvmlite module unavailable! can't assemble to LLVM IR...
```
Installing llvmlite fixes this problem.
However it is not listed as a dependency.

**Comment by aguinet** [comment]
This is a volontary non-mandatory dependency, because lots of parts of arybo can run without llvmlite, which involved having llvm installed at the time I wrote that code (and was thus a non negligeable dependency).

It's easier now that llvmlite provides wheels, but I still keep this optional for users that don't use the assembler part of arybo.
