### ISSUE TITLE
std::bad_alloc thrown in symbolic expression computation

### ISSUE THREAD

**Issue by tammela** [quarkslab/arybo#25]
The script to reproduce the issue is here:
```
from arybo.lib import MBA

def f(rdi, rsi, rdx, rcx, r8d):
   cse0Mult0 = (2816510611 * r8d)
   cse0Add1 = (1338184181 + (2816510611 * rdx))
   cse0Add2 = (2956783114 + (1478456685 * r8d))
   cse6Add4 = (1 + cse0Mult0)
   cse0BitOr0 = (cse0Add2 | (2956783114 + (1478456685 * rdx)))
   cse0BitOr1 = ((1338184181 + cse0Mult0) | cse0Add1)
   cse1Mult7 = ((cse6Add4 + cse0BitOr0) * ((3107144530 + (1438524315 * cse0BitOr1)) + (4294967295 * r8d)))
   cse0BitOr2 = (cse0Add1 | cse0Add2)
   cse2Mult13 = ((cse6Add4 + cse0BitOr2) * ((2856442981 + rdx) + (2856442981 * cse0BitOr2)))
   cse5Add12 = ((((((cse1Mult7 * 2816510611) + (2115068335 * rdx)) + (1338184181 * cse0BitOr1)) + (2115068335 * r8d)) + (1338184181 * cse0BitOr0)) + (cse2Mult13 * 2816510611))
   cse0Mult13 = (1478456685 * rdi)
   result = ((((cse5Add12 + 4294967293) + cse0Mult13) + (4294967295 * ((1618598933 + (2956913370 * rdi)) | ((((((1618598933 + (cse1Mult7 * 2956913370)) + (1618598934 * cse0BitOr0)) + (1618598934 * cse0BitOr1)) + (cse2Mult13 * 2956913370)) + (64830626 * r8d)) + (64830626 * rdx))))) + (4294967294 * ((2956783114 + cse0Mult13) | (cse5Add12 + 1338184181))))
   return result

mba = MBA(32)
rdi = mba.var('rdi')
rsi = mba.var('rsi')
rdx = mba.var('rdx')
rcx = mba.var('rcx')
r8d = mba.var('r8d')
ret = f(rdi, rsi, rdx, rcx, r8d)
print(ret)
```

Error is thrown here:
```
Traceback (most recent call last):
  File "ary-test", line 24, in <module>
    ret = f(rdi, rsi, rdx, rcx, r8d)
  File "ary-test", line 4, in f
    cse0Mult0 = (2816510611 * r8d)
  File "/home/vagrant/.local/lib/python3.7/site-packages/arybo/lib/mba_if.py", line 183, in __rmul__
    return self.__mul__(o)
  File "/home/vagrant/.local/lib/python3.7/site-packages/arybo/lib/mba_if.py", line 180, in __mul__
    return self.__call_op('mul', o)
  File "/home/vagrant/.local/lib/python3.7/site-packages/arybo/lib/mba_if.py", line 158, in __call_op
    ret = getattr(self.mba, fname)(self.vec, o)
  File "/home/vagrant/.local/lib/python3.7/site-packages/arybo/lib/mba_impl_petanque.py", line 323, in mul_n
    self.iadd_lshifted_Y(ret, X, i)
  File "/home/vagrant/.local/lib/python3.7/site-packages/arybo/lib/mba_impl_petanque.py", line 234, in iadd_lshifted_Y
    carry_new = simplify_inplace(mul_XY + (carry * Xi))
MemoryError: std::bad_alloc
```

I used a function sample that can be found [here](https://github.com/RUB-SysSec/syntia/blob/master/samples/tigress_mba_trace).

**Comment by aguinet** [comment]
Arybo can need lots of ram to store intermediate results, and I think that's what you are experimenting here.

Not really an easy workaround apart from having more temporary swap.
