### ISSUE TITLE
arybo latest on pip broken

### ISSUE THREAD

**Issue by sudhackar** [quarkslab/arybo#6]
```python

['__add__', '__and__', '__class__', '__cmp__', '__coerce__', '__delattr__', '__div__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__iadd__', '__iand__', '__idiv__', '__ilshift__', '__imod__', '__imul__', '__init__', '__invert__', '__ior__', '__irshift__', '__isub__', '__ixor__', '__le__', '__lshift__', '__lt__', '__mod__', '__mul__', '__ne__', '__neg__', '__new__', '__or__', '__radd__', '__rand__', '__rdiv__', '__reduce__', '__reduce_ex__', '__repr__', '__rlshift__', '__rmod__', '__rmul__', '__ror__', '__rrshift__', '__rshift__', '__rsub__', '__rxor__', '__setattr__', '__sizeof__', '__str__', '__sub__', '__subclasshook__', '__xor__', 'equalTo', 'evaluate', 'getBitvectorMask', 'getBitvectorSize', 'getChildren', 'getHash', 'getKind', 'getParents', 'getValue', 'isLogical', 'isSigned', 'isSymbolized', 'setChild']
Traceback (most recent call last):
  File "./solve-vm.py", line 760, in <module>
    retValue  = main()
  File "./solve-vm.py", line 670, in main
    M = generateLLVMExpressions(ctx, 0)
  File "./solve-vm.py", line 623, in generateLLVMExpressions
    e = tritonexprs2arybo(exprs)
  File "/home/sudhakar/.virtualenvs/sym/local/lib/python2.7/site-packages/arybo/tools/triton_.py", line 168, in tritonexprs2arybo
    e = tritonast2arybo(e.getAst(), True, False, context)
  File "/home/sudhakar/.virtualenvs/sym/local/lib/python2.7/site-packages/arybo/tools/triton_.py", line 31, in tritonast2arybo
    children_ = e.getChilds()
```

Although the version here in working fine. Just a heads up.

**Comment by aguinet** [comment]
That should be fixed with arybo 1.1.0 !
